- hosts: all
  connection: localhost
  roles:
    - name: ssh
      tags: ssh
      when: 'ansible_os_family == "Debian"'
      become: yes

    - name: anyenv
      tags: anyenv

    - name: pyenv
      tags: pyenv

    - name: pipenv
      tags: pipenv

    - name: webapp-dev
      tags: webapp-dev
